ALTER TABLE Users MODIFY Pass VARCHAR2(100) ENCRYPT USING 'AES256';

--or store only hashed password

CREATE OR REPLACE FUNCTION HashPassword(p_password VARCHAR2) RETURN VARCHAR2 AS 
BEGIN
    RETURN DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW(p_password, 'AL32UTF8'), DBMS_CRYPTO.HASH_SH256);
END;
